name: fluttter_socket_log_plugin
description: A new Flutter project.
version: 0.0.1
#homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.1
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0



flutter:

  plugin:
    platforms:
      android:
        package: com.khamidjon.fluttter_socket_log_plugin
        pluginClass: FluttterSocketLogPlugin
      ios:
        pluginClass: FluttterSocketLogPlugin
      macos:
        pluginClass: FluttterSocketLogPlugin

